# Generated by Django 6.0.7 on 2026-07-20 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_week',
            field=models.CharField(blank=True, max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'id_week must be exactly 3 digits (001-999).')]),
        ),
    ]
