# Generated by Django 6.0.7 on 2026-07-20 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_id_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_month',
            field=models.CharField(blank=True, max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'id_month must be exactly 4 digits (0001-9999).')]),
        ),
    ]
