# Generated by Django 6.0.7 on 2026-07-20 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_member', models.CharField(max_length=50, unique=True)),
                ('id_week', models.CharField(max_length=20)),
                ('id_month', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('guaranted_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_members', to='member.member')),
            ],
        ),
    ]
