# Generated by Django 6.0.7 on 2026-07-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_id_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('weekly', 'Mingguan'), ('monthly', 'Bulanan')], max_length=10, unique=True)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, help_text='Maksimal jumlah pinjaman', max_digits=15)),
                ('max_installments', models.PositiveIntegerField(help_text='Jumlah maksimal cicilan')),
            ],
        ),
    ]
