# Generated by Django 6.0.7 on 2026-07-24 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_id_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Saldo tabungan saat ini', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='member.member')),
            ],
            options={
                'verbose_name_plural': 'Savings',
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Setor'), ('withdrawal', 'Ambil')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Jumlah uang transaksi', max_digits=15)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Saldo sebelum transaksi', max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Saldo sesudah transaksi', max_digits=15)),
                ('transaction_date', models.DateField(help_text='Tanggal transaksi')),
                ('notes', models.TextField(blank=True, help_text='Catatan transaksi (opsional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('savings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='member.savings')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
