# Generated by Django 6.0.7 on 2026-07-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_add_loan_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, help_text='Jumlah pokok pinjaman', max_digits=15)),
                ('installment_count', models.PositiveIntegerField(help_text='Jumlah cicilan (bulan)')),
                ('installment_amount', models.DecimalField(decimal_places=2, help_text='Besar angsuran per bulan', max_digits=15)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0, help_text='Biaya administrasi', max_digits=15)),
                ('loan_rule', models.ForeignKey(help_text='Aturan pinjaman (hanya bulanan)', limit_choices_to={'loan_type': 'monthly'}, on_delete=django.db.models.deletion.CASCADE, related_name='rate_tables', to='member.loanrule')),
            ],
            options={
                'unique_together': {('loan_rule', 'loan_amount', 'installment_count')},
            },
        ),
    ]
